name: Build Kernel LTO

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: Kernel branch
        default: main
        required: true
      SELINUX_PERMISSIVE:
        description: Permissive SELinux
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ==========================================
      # Checkout Kernel
      # ==========================================
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          repository: ududuudydyhheheh-arch/exlinux-
          path: kernel_root
          ref: ${{ github.event.inputs.BRANCH }}
          fetch-depth: 0
          submodules: false

      # ==========================================
      # Prepare Dependencies
      # ==========================================
      - name: Prepare dependencies
        working-directory: kernel_root
        run: |
          sudo apt update -y
          sudo apt install -y \
            bc \
            cpio \
            flex \
            bison \
            git \
            python-is-python3 \
            tar \
            perl \
            wget \
            curl \
            lz4 \
            libssl-dev

      # ==========================================
      # Build Kernel
      # ==========================================
      - name: Build kernel
        id: buildKernel
        working-directory: kernel_root
        run: |
          export KBUILD_BUILD_USER="exlinux"
          export KBUILD_BUILD_HOST="github"
          export BUILD_START="$(date)"
          export IS_CI=true

          export DEFCONFIG="exlinux_defconfig"
          export DEVICE_ID="A12s"
          export DEVICE="A12s"

          # Set SELinux state based on input
          if [[ "${{ github.event.inputs.SELINUX_PERMISSIVE }}" == "true" ]]; then
            echo "SELinux state: Permissive"
            export SELINUX_PERMISSIVE=1
          else
            echo "SELinux state: Enforcing"
          fi

          bash ./build.sh kernel \
            --jobs "$(nproc --all)" \
            "$DEFCONFIG"

          mv .config build_config.txt

          gitsha1="$(git rev-parse --short HEAD)"
          kernelversion="$(make kernelversion)"

          buildDetails="${kernelversion}-${DEVICE_ID}_${gitsha1}-$(date +'%Y%m%d%H%M%S')"

          echo "buildDetails=$buildDetails" >> "$GITHUB_OUTPUT"

      # ==========================================
      # Upload Kernel
      # ==========================================
      - name: Upload kernel images
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-${{ steps.buildKernel.outputs.buildDetails }}
          path: |
            kernel_root/arch/arm64/boot/Image
            kernel_root/arch/arm64/boot/dts/exynos/*.dtb
            kernel_root/arch/arm64/boot/dts/samsung/*.dtb
